// const items = [
//   "Fixed Asset",
//   "Current Asset",
//   "Accounts Receivable",
//   "Non-current Liability",
//   "Current Liability",
//   "Accounts Payable",
//   "Revenue",
//   "Expense",
//   "Unpaid Expense Claims",
//   "Inventory",
//   "Historical Adjustment",
//   "Bank Revaluations",
//   "Direct Costs",
//   "Equity",
//   "Rounding",
//   "Retained Earnings",
//   "Sales Tax",
//   "Tracking",
//   "Wages Payable",
//   "Realized Currency Gains",
//   "Unrealized Currency Gains",
// ];
const items = [
  "CURRENT",
  "FIXED",
  "INVENTORY",
  "NONCURRENT",
  "PREPAYMENT",
  "EQUITY",
  "DEPRECIATN",
  "DIRECTCOSTS",
  "EXPENSE",
  "OVERHEADS",
  "CURRLIAB",
  "LIABILITY",
  "TERMLIAB",
  "OTHERINCOME",
  "REVENUE",
  "SALES",

  "DEBTORS",
  "CREDITORS",
  "UNPAIDEXPCLM",
  "HISTORICAL",
  "BANKCURRENCYGAIN",
  "ROUNDING",
  "RETAINEDEARNINGS",
  "TRACKINGTRANSFERS",
  "WAGEPAYABLES",
  "REALISEDCURRENCYGAIN",
  "UNREALISEDCURRENCYGAIN",
];

export default items;
